--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/stringutils
branches:
  - main
projects:
  stringutils:
    model: virion
    type: library
    icon: assets/icon.png
    lint:
      phpstan: false
...
